# Generated by Django 2.0.6 on 2018-06-26 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StruggleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('time_started', models.DateTimeField(default=datetime.datetime.now)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('struggle', models.TextField()),
                ('plan', models.TextField(verbose_name='plan of action')),
                ('frustration_level', models.IntegerField(verbose_name='frustration level (Rate 0 to 10)')),
                ('learning_level', models.IntegerField(blank=True, null=True, verbose_name='learning level (Rate 0 to 10)')),
                ('code_screen_shot', models.FileField(blank=True, null=True, upload_to='')),
                ('code_screen_shot_update', models.FileField(blank=True, null=True, upload_to='')),
                ('review_learning', models.TextField(blank=True, null=True)),
                ('struggle_in_progess', models.BooleanField(default=True)),
                ('helpful_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-time_started', 'title'],
            },
        ),
    ]
