# Generated by Django 2.0.6 on 2018-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struggle_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='struggledata',
            options={'ordering': ['-time_started', 'title'], 'verbose_name_plural': 'struggle data'},
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='struggle_in_progess',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='time_ended',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
