# Generated by Django 2.0.6 on 2018-06-21 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struggle_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struggledata',
            name='time_ended',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 13, 32, 33, 900324)),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 13, 32, 33, 900294)),
        ),
    ]
