# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struggle_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struggledata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
