# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struggle_input', '0002_auto_20180606_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struggledata',
            name='code_screen_shot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='plan',
            field=models.TextField(help_text='Enter your plan of action here'),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='struggle',
            field=models.TextField(help_text='Enter your struggles here'),
        ),
    ]
