# Generated by Django 2.0.6 on 2018-06-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struggle_input', '0002_auto_20180621_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struggledata',
            name='learning_level',
            field=models.IntegerField(default=5, verbose_name='learning level (Rate 0 to 10)'),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='struggle_in_progess',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='struggledata',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
