# Generated by Django 2.0.6 on 2018-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struggle_input', '0003_auto_20180621_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struggledata',
            name='learning_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='learning level (Rate 0 to 10)'),
        ),
    ]
